version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: America/New_York
  groups:
    sitepress:
      patterns:
        - "sitepress*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: America/New_York
  groups:
    github_actions:
      patterns:
        - "*"
